Bizeducate_website/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

bizeducate_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls", namespace="website"))
]

website/urls.py
from django.urls import path
from website.views import Index


urlpatterns = [
    path("",index, name="index")
]

website/models.py
import datetime

from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "countries"

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Trainer(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    qualification = models.CharField(max_length=500, blank=True)
    profile = models.TextField(max_length=1000, blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, blank=True, related_name="trainers")

    def __str__(self):
        return f"Trainer: {self.first_name} {self.last_name}"


class Course(models.Model):
    title = models.CharField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, blank=True, related_name="courses")
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING, blank=True, related_name="courses")
    course_date = models.DateField(datetime.date, blank=True)
    duration = models.DurationField(max_length=2,  blank=True)
    overview = models.TextField(max_length=1000, blank=True)
    trainers = models.ManyToManyField(Trainer, related_name="courses")

    class Meta:
        ordering = ["-course_date"]

    def __str__(self):
        return self.title

website/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block title %}
    <title>Document</title>
  {% endblock %}
  {% load static %}

  <link rel="stylesheet" href="{% static "fonts" %}">
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600%7cPlayfair+Display:400i" rel="stylesheet">
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

  <link rel="stylesheet" href="{% static "css/plugins.min.css" %}">
  <link rel="stylesheet" href="{% static "css/template.css" %}">



</head>
<body>
<!-- Preloader-->
  <div class="page-loader">
    <div class="page-loader-inner">
      <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
      </div>
    </div>
  </div>
<!-- Preloader end-->

<!-- Header-->
  <header class="header header-transparent">
    <div class="container-fluid">
      <!-- Brand-->
      <div class="inner-header"><a class="inner-brand" href="{% url "website:index" %}">Bizeducate</a></div>
      <!-- Navigation-->
      <div class="inner-navigation collapse">
        <div class="inner-nav">
          <ul>
            <li class="menu-item-has-children menu-item-has-mega-menu"><a href="#"><span class="menu-item-span">Home</span></a>
              <div class="mega-menu">
                <ul class="sub-menu mega-menu-row" data-background="assets/images/menu-3.jpg">
                  <!-- Column 1-->
                  <li class="menu-item-has-children mega-menu-col"><a href="#">Multi Page</a>
                    <ul class="sub-menu">
                      <li><a href="#">Parallax</a></li>
                      <li><a href="#">Slider - Fade</a></li>
                      <li><a href="#">Slider - Slide</a></li>
                    </ul>
                  </li>
                  <!-- Column 2-->
                  <li class="menu-item-has-children mega-menu-col"><a href="#">One Page</a>
                    <ul class="sub-menu">
                      <li><a href="#">Parallax</a></li>
                      <li><a href="#">Slider - Fade</a></li>
                      <li><a href="#">Slider - Slide</a></li>
                      <li><a href="#">Gradient Style 1</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </li>
            <li class="menu-item-has-children menu-item-has-mega-menu"><a href="#"><span class="menu-item-span">Pages</span></a>
              <div class="mega-menu">
                <ul class="sub-menu mega-menu-row" data-background="assets/images/menu-1.jpg">
                  <!-- Column 1-->
                  <li class="menu-item-has-children mega-menu-col"><a href="#">Pages 1</a>
                    <ul class="sub-menu">
                      <li><a href="#">About Us 1</a></li>
                      <li><a href="#">About Us 2</a></li>
                    </ul>
                  </li>
                  <!-- Column 2-->
                  <li class="menu-item-has-children mega-menu-col"><a href="#">Pages 2</a>
                    <ul class="sub-menu">
                      <li><a href="#">Sign in</a></li>
                      <li><a href="#">Sign Up</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </li>
            <li class="menu-item-has-children"><a href="#"><span class="menu-item-span">Portfolio</span></a>
              <ul class="sub-menu">
                <li><a href="#">Carousel</a></li>
                <li class="menu-item-has-children"><a href="#">Wide</a>
                  <ul class="sub-menu">
                    <li><a href="#">5 Columns</a></li>
                    <li><a href="#">4 Columns</a></li>
                  </ul>
                </li>
                <li class="menu-item-has-children"><a href="#">Boxed</a>
                  <ul class="sub-menu">
                    <li><a href="#">4 Columns</a></li>
                    <li><a href="#">3 Columns</a></li>
                  </ul>
                </li>
                <li class="menu-item-has-children"><a href="#">Single</a>
                  <ul class="sub-menu">
                    <li><a href="#">Sidebar Stack</a></li>
                    <li><a href="#">Sidebar Slides</a></li>
                    <li><a href="#">Sidebar Gallery</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li class="menu-item-has-children"><a href="#"><span class="menu-item-span">Blog</span></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="extra-nav">
        <ul>
          <li><a class="top-bar-cart" href="#"><span class="menu-item-span"><i class="ti-shopping-cart"></i><span>3</span></span></a></li>
          <li><a class="off-canvas-open" href="#"><span class="menu-item-span"><i class="ti-menu"></i></span></a></li>
          <li class="nav-toggle"><a href="#" data-toggle="collapse" data-target=".inner-navigation"><span class="menu-item-span"><i class="ti-menu"></i></span></a></li>
        </ul>
      </div>
    </div>
  </header>
<!-- Header end-->
<!-- Wrapper-->
  <div class="wrapper">
    {% block content %}
    {% endblock %}


  <!-- Footer-->
    <footer class="footer">
      <div class="footer-widgets">
        <div class="container">
          <div class="row">
            <div class="col-md-3">
              <!-- Text widget-->
              <aside class="widget widget-text">
                <div class="widget-title">
                  <h6>About Us</h6>
                </div>
                <div class="textwidget">
                  <p>Map where your photos were taken and discover local points of interest. Map where your photos.</p>
                  <ul class="social-icons">
                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                  </ul>
                </div>
              </aside>
            </div>
            <div class="col-md-3">
              <!-- Recent entries widget-->
              <aside class="widget widget-recent-entries">
                <div class="widget-title">
                  <h6>Recent Posts</h6>
                </div>
                <ul>
                  <li><a href="#">Map where your photos were taken and discover local points.</a><span class="post-date">May 8, 2018</span></li>
                  <li><a href="#">Map where your photos were taken and discover local points.</a><span class="post-date">April 7, 2018</span></li>
                  <li><a href="#">Map where your photos were taken and discover local points.</a><span class="post-date">September 7, 2018</span></li>
                </ul>
              </aside>
            </div>
            <div class="col-md-3">
              <!-- Recent works-->
              <aside class="widget widget-recent-works">
                <div class="widget-title">
                  <h6>Portfolio</h6>
                </div>
                <ul>
                  <li><a href="#"><img src="{% static "images/widgets/1.jpg" %}" alt=""></a></li>
                  <li><a href="#"><img src="{% static "images/widgets/2.jpg" %}" alt=""></a></li>
                  <li><a href="#"><img src="{% static "images/widgets/3.jpg" %}" alt=""></a></li>
                </ul>
              </aside>
            </div>
            <div class="col-md-3">
              <!-- Twitter widget-->
              <aside class="widget twitter-feed-widget">
                <div class="widget-title">
                  <h6>Contact</h6>
                </div>
                <div class="textwidget">
                  <p>
                    Location: 12 London Avenue, Suite 18<br>
                    E-mail: support@theme.com<br>
                    Phone: 8 800 123 4567<br>
                  </p>
                </div>
              </aside>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bar">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="copyright">
                <p>© 2008-2024 Bizeducate Ltd., All Rights Reserved.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Footer end-->
  </div>
  <!-- Wrapper end-->
        <!-- Off canvas-->
{#        <div class="off-canvas-sidebar">#}
{#            <div class="off-canvas-sidebar-wrapper">#}
{#                <div class="off-canvas-header"><a class="off-canvas-close" href="#"><span class="ti-close"></span></a></div>#}
{#                <div class="off-canvas-content">#}
{#                    <!-- Text widget-->#}
{#                    <aside class="widget widget-text">#}
{#                        <div class="textwidget">#}
{#                            <p class="text-center"><img src="assets/images/logo-light-2.png" alt="" width="80px"></p>#}
{#                            <p class="text-center">See how users experience your website in realtime to see changes.</p>#}
{#                        </div>#}
{#                    </aside>#}
{#                    <!-- Recent portfolio widget-->#}
{#                    <aside class="widget widget-recent-works">#}
{#                        <ul>#}
{#                            <li><a href="#"><img src="assets/images/widgets/1.jpg" alt=""></a></li>#}
{#                            <li><a href="#"><img src="assets/images/widgets/2.jpg" alt=""></a></li>#}
{#                            <li><a href="#"><img src="assets/images/widgets/3.jpg" alt=""></a></li>#}
{#                            <li><a href="#"><img src="assets/images/widgets/4.jpg" alt=""></a></li>#}
{#                            <li><a href="#"><img src="assets/images/widgets/5.jpg" alt=""></a></li>#}
{#                            <li><a href="#"><img src="assets/images/widgets/6.jpg" alt=""></a></li>#}
{#                            <li><a href="#"><img src="assets/images/widgets/7.jpg" alt=""></a></li>#}
{#                            <li><a href="#"><img src="assets/images/widgets/8.jpg" alt=""></a></li>#}
{#                            <li><a href="#"><img src="assets/images/widgets/9.jpg" alt=""></a></li>#}
{#                        </ul>#}
{#                    </aside>#}
{#                    <!-- Social Icons-->#}
{#                    <ul class="social-icons text-center">#}
{#                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>#}
{#                        <li><a href="#"><i class="fab fa-instagram"></i></a></li>#}
{#                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>#}
{#                        <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
        <!-- Off canvas end-->

  <!-- To top button--><a class="scroll-top" href="#top"><i class="fas fa-angle-up"></i></a>
<script src="{% static 'js/custom/jquery.min.js' %}"></script>
<script src="{% static 'js/custom/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'js/custom/plugins.min.js' %}"></script>
<script src="{% static 'js/custom/custom.min.js' %}"></script>
</body>
</html>

templates/includes/counters.html
{% load static %}
<section class="module parallax" data-background="{% static "images/module-1.jpg" %}" data-overlay="0.5">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="counter">
              <div class="counter-icon"><span class="icon-energy icons"></span></div>
              <div class="counter-number">
                <h6><strong class="counter-timer" data-from="0" data-to="350">0</strong></h6>
              </div>
              <div class="counter-title">Organised Courses</div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="counter">
              <div class="counter-icon"><span class="icon-mustache icons"></span></div>
              <div class="counter-number">
                <h6><strong class="counter-timer" data-from="0" data-to="1160">0</strong></h6>
              </div>
              <div class="counter-title">Participated Professionals</div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="counter">
              <div class="counter-icon"><span class="icon-fire icons"></span></div>
              <div class="counter-number">
                <h6><strong class="counter-timer" data-from="0" data-to="11">0</strong></h6>
              </div>
              <div class="counter-title">Countries of Organised Trainings</div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="counter">
              <div class="counter-icon"><span class="icon-diamond icons"></span></div>
              <div class="counter-number">
                <h6><strong class="counter-timer" data-from="0" data-to="14">0</strong></h6>
              </div>
              <div class="counter-title">Years on Market</div>
            </div>
          </div>
        </div>
      </div>
    </section>

templates/includes/courses_categories.html
<section class="module divider-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-6 m-auto text-center">
            <h1>Areas of Our Courses</h1>
            <p class="lead">See how your users experience your website in realtime or view trends to see any changes in performance over time.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="space" data-MY="60px"></div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="icon-box text-center">
              <div class="icon-box-icon"><span class="ti-layout"></span></div>
              <div class="icon-box-title">
                <h6>Visual Composer</h6>
              </div>
              <div class="icon-box-content">
                <p>Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam lorem ipsum amet.</p>
              </div>
              <div class="icon-box-link"><a href="#">Read more</a></div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="icon-box text-center">
              <div class="icon-box-icon"><span class="ti-cup"></span></div>
              <div class="icon-box-title">
                <h6>Revolution Slider</h6>
              </div>
              <div class="icon-box-content">
                <p>Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam lorem ipsum amet.</p>
              </div>
              <div class="icon-box-link"><a href="#">Read more</a></div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="icon-box text-center">
              <div class="icon-box-icon"><span class="ti-harddrives"></span></div>
              <div class="icon-box-title">
                <h6>User Experience</h6>
              </div>
              <div class="icon-box-content">
                <p>Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam lorem ipsum amet.</p>
              </div>
              <div class="icon-box-link"><a href="#">Read more</a></div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="icon-box text-center">
              <div class="icon-box-icon"><span class="ti-desktop"></span></div>
              <div class="icon-box-title">
                <h6>Fully Responsive</h6>
              </div>
              <div class="icon-box-content">
                <p>Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam lorem ipsum amet.</p>
              </div>
              <div class="icon-box-link"><a href="#">Read more</a></div>
            </div>
          </div>
        </div>
      </div>
  </section>

templates/includes/upcoming_events.html
{% load static %}
<section class="module">
      <div class="container">
        <div class="row">
          <div class="col-md-6 m-auto text-center">
            <h1>Upcoming Events</h1>
            <p class="lead">See how your users experience your website in realtime or view trends to see any changes in performance over time.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="space" data-MY="60px"></div>
          </div>
        </div>
        <div class="row row-post-masonry">
          {% for course in courses %}
            <div class="col-md-4 post-item">
            <!-- Post-->
              <article class="post">
                <div class="post-preview"><a href="#"><img src="{% static "images/blog/1.jpg" %}" alt=""></a></div>
                <div class="post-wrapper">
                  <div class="post-header">
                    <h2 class="post-title"><a href="#">{{ course.title }}</a></h2>
                  </div>
                  <div class="post-content">
                    <p>{{  course.country }}</p>
                    <p><a href="#">Read more</a></p>
                  </div>
                </div>
              </article>
            <!-- Post end-->
            </div>
          {% endfor %}
{#          <div class="col-md-4 post-item">#}
{#            <!-- Post-->#}
{#            <article class="post">#}
{#              <div class="post-preview"><a href="#"><img src="{% static "images/blog/3.jpg" %}" alt=""></a></div>#}
{#              <div class="post-wrapper">#}
{#                <div class="post-header">#}
{#                  <h2 class="post-title"><a href="#">Minimalist Chandelier</a></h2>#}
{#                </div>#}
{#                <div class="post-content">#}
{#                  <p>See how your users experience your website in realtime or view trends to see any changes in performance over time.</p>#}
{#                  <p><a href="#">Read more</a></p>#}
{#                </div>#}
{#              </div>#}
{#            </article>#}
{#            <!-- Post end-->#}
{#          </div>#}
{#          <div class="col-md-4 post-item">#}
{#            <!-- Post-->#}
{#            <article class="post">#}
{#              <div class="post-preview"><a href="#"><img src="{% static "images/blog/5.jpg" %}" alt=""></a></div>#}
{#              <div class="post-wrapper">#}
{#                <div class="post-header">#}
{#                  <h2 class="post-title"><a href="#">Standard Shape</a></h2>#}
{#                </div>#}
{#                <div class="post-content">#}
{#                  <p>See how your users experience your website in realtime or view trends to see any changes in performance over time.</p>#}
{#                  <p><a href="#">Read more</a></p>#}
{#                </div>#}
{#              </div>#}
{#            </article>#}
{#            <!-- Post end-->#}
{#          </div>#}
        </div>
      </div>
    </section>

templates/website/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Slider-->
    <section class="module-cover-slides fullscreen">
      <ul class="slides-container">
        <li class="parallax text-center" data-overlay="0.5"><img src="{% static 'images/london_city.jpg' %}" alt="">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h1 class="m-b-20"><strong>Yes, We Can Build That</strong></h1>
                <p class="m-b-40">See how your users experience your website in realtime or view  <br> trends to see any changes in performance over time.</p>
                <p><a class="btn btn-lg btn-circle btn-warning" href="#">Get Started</a><a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Learn More</a></p>
              </div>
            </div>
          </div>
        </li>
        <li class="parallax text-center" data-overlay="0.5"><img src="{% static "images/module-1.jpg" %}" alt="">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h1 class="m-b-20"><strong>Gear up to land <br> somewhere new.</strong></h1>
                <p class="m-b-40">See how your users experience your website in realtime or view  <br> trends to see any changes in performance over time.</p>
                <p><a class="btn btn-lg btn-circle btn-brand" href="#">Get Started</a><a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Learn More</a></p>
              </div>
            </div>
          </div>
        </li>
        <li class="parallax text-center" data-overlay="0.7" data-gradient="1"><img src="{% static "images/module-25.jpg" %}" alt="">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h1 class="m-b-20"><strong>Your customers will love you <br> one minute from now.</strong></h1>
                <p class="m-b-40">See how your users experience your website in realtime or view  <br> trends to see any changes in performance over time.</p>
                <p><a class="btn btn-lg btn-circle btn-new-white" href="#">Get Started</a><a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Learn More</a></p>
              </div>
            </div>
          </div>
        </li>
      </ul>
      <div class="slides-navigation"><a class="prev" href="#"><span class="ti-angle-left"></span></a><a class="next" href="#"><span class="ti-angle-right"></span></a></div>
    </section>
    <!-- Slider end-->

    <!-- Categories-->
    {% block categories %}
      {% include "includes/courses_categories.html" %}
    {% endblock %}
    <!-- Categories end-->

    <!-- Counters-->
    {% block counters %}
      {% include "includes/counters.html" %}
    {% endblock %}
    <!-- Counters end-->

    <!-- Upcoming events-->
    {% block upcoming_events %}
      {% include "includes/upcoming_events.html" %}
    {% endblock %}
    <!-- Upcoming events end-->

{% endblock %}